name: bot_t_2
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  teledart: ^0.3.4
  faker: any
  csv: ^5.0.1
  #csv_sheet: any

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
